apiVersion: v1
kind: Service
metadata:
  name: fastify-workspace-api
spec:
  selector:
    app: fastify-workspace-api
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: grpc
      port: 50051
      targetPort: grpc
